spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS LOZM
    username: laonzenamoon
    password: laonzenamoon
    testQuery: "SELECT 1"
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 500
        jdbc:
          batch_size: 100
          order_inserts: true
      format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
