server:
  port: 8880

spring:
  application:
    name: community-api
  jpa.hibernate.ddl-auto: none
  profiles:
    active: local

logging:
  level:
    root: info
    me.lozm: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    org.hibernate.SQL: debug
