server:
  port: 8880

spring:
  application:
    name: community-api
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 1000
        order_inserts: true
        order_updates: true
    open-in-view: false
  cache:
    ehcache:
      config: classpath:ehcache.xml

logging:
  level:
    root: info

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ReadTimeout: 5000
  ConnectTimeout: 1000
  MaxTotalConnections: 300
  MaxConnectionsPerHost: 100
  retryableStatusCodes: 500

eureka:
  client:
    enabled: false

decorator:
  datasource:
    p6spy:
      enable-logging: false
      log-format: '#%(connectionId) | %(executionTime)ms | %(category) | %(sql)'
