server:
  port: 8880

spring:
  application:
    name: community-api
  jpa.hibernate.ddl-auto: none
  profiles:
    active: local

logging:
  level:
    root: info

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ReadTimeout: 5000
  ConnectTimeout: 1000
  MaxTotalConnections: 300
  MaxConnectionsPerHost: 100
  retryableStatusCodes: 500

eureka:
  client:
    enabled: false

decorator:
  datasource:
    p6spy:
      enable-logging: false
      log-format: '#%(connectionId) | %(executionTime)ms | %(category) | %(sql)'
