spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS LOZM
    username: laonzenamoon
    password: laonzenamoon
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 500
        jdbc:
          batch_size: 100
          order_inserts: true
      format_sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
      log-format: '#%(connectionId) | %(executionTime)ms | %(category) | %(sql)'
